# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v3

      # Generates the snake using a script
      - name: Generate snake gif and svg
        run: |
          docker run --rm -v $(pwd):/usr/src/app -w /usr/src/app node:20 bash -c "
          git clone https://github.com/Platane/snk.git
          cd snk
          npm install
          npm run build
          npm run start --user shailum17 --gif dist/github-contribution-grid-snake.gif --svg dist/github-contribution-grid-snake.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated snake
          branch: master
          file_pattern: dist/*

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          # The output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
