# .github/workflows/metrics.yml
name: Metrics

on:
  # Schedule daily updates (adjust cron as needed)
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main (optional)
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To commit the generated files
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Use your PAT from repository secrets
          user: shailum17 # Your GitHub username
          template: classic # You can experiment with other templates like `terminal`, `repository`, etc.
          # Base metrics
          base: |
            header
            activity
            community
            repositories
            metadata
          config_display: columns
          config_padding: 0, 10 # Adjust padding if needed
          config_output: svg
          filename: output/github-profile-summary.svg # Output path

          # Core GitHub Stats (replaces anuraghazra's for consistency)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_isocalendar_light: "#ebedf0" # Adjust if you have a light theme or prefer a different color

          # GitHub Stats from metrics
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_introduction_description: yes

          # Languages
          plugin_languages: yes
          plugin_languages_sections: |
            most-used
            recently-used
          plugin_languages_threshold: 0% # Show all languages
          plugin_languages_details: bytes-size, percentage # Display more details
          plugin_languages_limit: 10 # Number of languages to show
          plugin_languages_other: yes # Include "Other" category
          filename_languages: output/github-languages.svg

          # Stargazers (show your starred repositories)
          plugin_stars: yes
          filename_stars: output/github-stars.svg

          # Topics (show topics you frequently use in your repos)
          plugin_topics: yes
          plugin_topics_limit: 10 # Number of topics to show
          filename_topics: output/github-topics.svg

          # Lines of code (advanced, requires more permissions usually)
          # Make sure your PAT has `repo` scope for this to work well
          plugin_lines: yes
          plugin_lines_history: yes
          plugin_lines_sections: |
            code
            commits
            additions
            deletions
          filename_lines: output/github-lines.svg

          # Activity
          plugin_activity: yes
          plugin_activity_limit: 5 # Number of recent activities to show
          plugin_activity_days: 14 # Activity within the last X days
          filename_activity: output/github-activity.svg

          # GitHub Trophies (requires `ryo-ma/github-profile-trophy` if you want this specific style,
          # or use metrics' own achievement plugin)
          # For consistency with the rest, let's use lowlighter/metrics's achievements plugin
          plugin_achievements: yes
          plugin_achievements_threshold: C # Display achievements above this rank
          plugin_achievements_secrets: yes # If you want to show secret achievements
          filename_achievements: output/github-trophies.svg # This will be the new trophy image

          # Optional: WakaTime for coding activity stats (requires WakaTime API key as a secret)
          # If you want this, create a secret called `WAKATIME_TOKEN` with your WakaTime API Key
          # plugin_wakatime: yes
          # plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          # plugin_wakatime_sections: time, projects, languages, editors, os, daily
          # plugin_wakatime_limit: 5
          # filename_wakatime: output/github-wakatime.svg

          # Set theme for all metrics images
          config_timezone: Asia/Kolkata # Important for accurate time tracking
          config_units: metric # Or imperial
          config_order: default # Or custom order if you want to rearrange
          config_octicon: yes # Use GitHub's octicons where available
          config_animated: yes # Enable animations
          config_icons: yes # Show icons next to titles
          config_font: monospace # Or other font options

          # Choose a theme
          # For dark:
          # config_variants: dark:tokyonight
          # For light (or if you prefer a different look):
          config_variants: light:solarized-light # Example light theme
          # config_variants: dark:gruvbox # Another dark theme example
